
@baseUrl = Http://localhost:3000

# Recados

### lista apenas um recado
GET {{baseUrl}}/recados/24/
###
GET {{baseUrl}}/recados/
?limit=10
&offset=0
Authorization: 'Bearer TokemUsuario'
###Criar um recado
POST {{baseUrl}}/recados/
Content-Type: application/json

{
  "texto": "pode ser vazia",
  "deId": 6,
  "paraId": 8
}

### Atualizar Recado
PATCH {{baseUrl}}/recados/24/
Content-Type: application/json

{
  "texto": "recado atualizado"
 
}

### apaga um recado
DELETE {{baseUrl}}/recados/5/


#


# Pessoas
### Lista todas as pessoas
GET {{baseUrl}}/pessoas/
?limit=10
&offset=0
### Lista apenas uma pessoa
GET {{baseUrl}}/pessoas/8/
### Cria uma pessoa
POST {{baseUrl}}/pessoas/
Content-Type: application/json

{
    "email": "oli.bruna06@gmail.com",
    "password": "23505",
    "nome": "Bruna"
}
### Atualizar Pessoa
PATCH {{baseUrl}}/pessoas/8/
Content-Type: application/json

{
    "password":"242526",
    "nome":"Kelven"
 
}

### apaga a pessoa
DELETE {{baseUrl}}/pessoas/3/







### Exemplo de Rota

# @name ExemplodeRota
GET  {{baseUrl}}/home/exemplo/


### AppControllerGetHello

# @name AppControllerGetHello
GET  {{baseUrl}}/home/hello/

### Conceitos Manual Controller Home

# @name ConceitosManualControllerHome
GET  {{baseUrl}}/conceitos-manual/

### Conceitos Automatico Controller Home

# @name ConceitosAutomaticoControllerHome
GET  {{baseUrl}}/conceitos-automatico/