
@baseUrl = Http://localhost:3000

# Recados

### lista apenas um recado
GET {{baseUrl}}/recados/6/
###
GET {{baseUrl}}/recados/
###Criar um recado
POST {{baseUrl}}/recados/
Content-Type: application/json

  {
    "texto": "2 Novo recado",
    "de": "Bruna",
    "para": "Kelven"
    
  }
### Atualizar Recado
PATCH {{baseUrl}}/recados/8/
Content-Type: application/json

{
  "texto": "recado atualizado"
 
}

### apaga um recado
DELETE {{baseUrl}}/recados/5/


#


# Pessoas
### Lista todas as pessoas
GET {{baseUrl}}/pessoas/
?limit=10
&offset=0
### Lista apenas uma pessoa
GET {{baseUrl}}/pessoas/3/
### Cria uma pessoa
POST {{baseUrl}}/pessoas/
Content-Type: application/json
{
    "texto": "email1@email.com",
    "de": "123456",
    "para": "Luiz"
}







### Exemplo de Rota

# @name ExemplodeRota
GET  {{baseUrl}}/home/exemplo/


### AppControllerGetHello

# @name AppControllerGetHello
GET  {{baseUrl}}/home/hello/

### Conceitos Manual Controller Home

# @name ConceitosManualControllerHome
GET  {{baseUrl}}/conceitos-manual/

### Conceitos Automatico Controller Home

# @name ConceitosAutomaticoControllerHome
GET  {{baseUrl}}/conceitos-automatico/